AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'db/**/*'
  TargetRubyVersion: 3.1.1
  SuggestExtensions: false

  Style/BlockComments:
    Enable: false

  Style/Documentation:
    Enable: false